/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  homeSidebar: [{type: 'doc', id: 'getting-started'}],
  javascriptSidebar: [{type: 'autogenerated', dirName: 'javascript'}],
  jquerySidebar: [{type: 'autogenerated', dirName: 'jquery'}],
  angularSidebar: [{type: 'autogenerated', dirName: 'angular'}],
  reactSidebar: [{type: 'autogenerated', dirName: 'react'}],
  frameworkLinks: [
    {
      type: 'link',
      label: 'Mobiscroll for Javascript', 
      href: 'javascript/getting-started',
    },
    {
      type: 'link',
      label: 'Mobiscroll for jQuery', 
      href: 'jquery/getting-started',
    },
    {
      type: 'link',
      label: 'Mobiscroll for React', 
      href: 'react/getting-started',
    },
    {
      type: 'link',
      label: 'Mobiscroll for Angular', 
      href: 'angular/getting-started',
    },
  ],
};

module.exports = sidebars;


